package constants

const (
	ERR_DATASET_NOT_FOUND              = "dataset not found"
	ERR_DATASET_ID_IS_REQUIRED         = "dataset id is required"
	ERR_DATASET_VERSION_IS_REQUIRED    = "dataset version is required"
	ERR_DATASET_ID_INVALID_FORMAT      = "dataset id must contain only lowercase english letters, underscore, and hyphen without spaces"
	ERR_DATASET_VERSION_INVALID_FORMAT = "dataset version must contain be in format v1.0.0"
	ERR_DATASET_VERSION_ALREADY_EXISTS = "dataset version already exists"
	ERR_INVALID_REQUEST_BODY           = "invalid request body"
	ERR_SOURCE_NOT_FOUND               = "source not found"
	ERR_SCHEMA_NOT_FOUND               = "schema not found"
	ERR_TABLE_NOT_FOUND                = "table not found"
	ERR_COLUMN_NOT_FOUND               = "column not found"
	ERR_INVALID_SOURCE_ID              = "invalid source id"
	ERR_DATASET_VERSION_NOT_FOUND      = "dataset version not found"
	ERR_INVALID_EXPORT_JOB_ID          = "invalid export job id"
	ERR_EXPORT_JOB_NOT_FOUND           = "export job not found"
	ERR_PERMISSION_DENIED              = "permission denied"
	ERR_SOURCE_NAME_ALREADY_EXISTS     = "source name already exists"
	ERR_OWNER_CLAIM_MISSING            = "owner-based filtering is configured but the required token claim is missing from your JWT"
	ERR_OWNER_CLAIM_EMPTY              = "owner-based filtering is configured but the token claim value is empty"
	ERR_WRITE_POLICY_TABLE_NOT_FOUND   = "write policy allow_edit requires a valid table in query.from but the table was not found in source"
	ERR_WRITE_POLICY_TABLE_REQUIRED    = "write policy allow_edit requires query.from.table to be specified"
)
