services:
  sms-data-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: sms-data-service
    env_file: .env
    networks:
      - sms-project
    ports:
      - 3000:3000
      - 3100:3100
    volumes:
      - .:/go/src/github.com/IT-CP25-US1-School-Management-System/sms-data-service

networks:
  sms-project:
    external: true
    name: sms
