version: "3"
services:
  sms-data-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: sms-data-service
    env_file: .env
    networks:
      - default
    ports:
      - 3000:3000
      - 3100:3100
    volumes:
      - .:/go/src/github.com/IT-CP25-US1-School-Management-System/sms-data-service

networks:
  default:
    external:
      name: sms
